FROM ruby:3.2.1

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN gem update --system
RUN gem update bundler
RUN bundle install

EXPOSE 4567

CMD ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "4567"]
