FROM ruby:3.2.1

ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
    libpq-dev \
    postgresql-client

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN gem update --system
RUN gem update bundler
RUN bundle install

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
